FROM python:latest

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

ENTRYPOINT ["python"]

# This command will be overrun on Kubernetes to run other init containers.
CMD ["manage.py", "runserver", "0.0.0.0:8000"]
