FROM python:latest

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt && \
    python manage.py collectstatic

CMD ["gunicorn", "naspo_price_project.wsgi:application", "--bind", "0.0.0.0:8000"]
