FROM nginx:latest

COPY nginx/ /etc/nginx/conf.d/

RUN apt update && \ 
    apt install -y libnss3-tools mkcert && \
    mkcert -install && \
    mkcert localhost 127.0.0.1 ::1

EXPOSE 80

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]