apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: django-app-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack-1759266157
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: naspo-django-app
  podMetricsEndpoints:
  - port: "8000"
    path: /metrics
    interval: 10s