apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: django-app-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack-1759426471
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: naspo-django-app
  podMetricsEndpoints:
  - port: https
    path: /metrics
    interval: 10s
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    authorization:
      credentials:
        name: bearer-token
        key: token